config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :folders
  resources :rooms, except: %i[index] do
    resources :documents, except: %i[index] do
      member do
        get :download
      end
    end
  end

  resources :user_controll_rooms, only: [:create, :destroy]

  devise_for :users, only: %i[sign_in sign_up sessions registrations]
  root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/folder.rb
class Folder < ApplicationRecord
  validates :name, presence: true

  # [gem 'ancestry'](https://github.com/stefankroes/ancestry)
  #  L フォルダを階層化するため追加(経路列挙(Path Enumeration))
  has_ancestry

  belongs_to :user
  has_many   :rooms, dependent: :destroy

  scope :order_by_preference, -> { order(id: :desc) }
  scope :unset_root, -> { where.not(name: 'Root', ancestry: nil) }

  # ルートフォルダを返す
  def self.summit
    find_by(name: 'Root', ancestry: nil)
  end

  # 子フォルダ全てを取得する(foldersテーブルとroomsテーブルの値を取得)
  # ex) rootフォルダより下のフォルダを取得
  #       L folder01
  #       L folder02
  #       L room01
  def all_childrens
    childrens = []

    children.each do |child|
      childrens << child
    end

    rooms.each do |child|
      childrens << child
    end
    childrens
  end

  # rootから始まりselfで終わるレコードのパス(rootフォルダは含まない)
  def root_below_folder
    path.unset_root
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  include CrudActionsMixin

  def index
    @resource = Folder.summit
    @resources = @resource.all_childrens.sort_by { |r, _| r.created_at }.reverse
  end

  def show
    @resources = @resource.all_childrens.sort_by { |r, _| r.created_at }.reverse
    @root_below_folder = @resource.root_below_folder
  end

  private

  def resource_params
    params.require(:folder).permit(:name, :description, :ancestry, :parent_id, :user_id)
  end

  def new_resource
    @resource = model_name.new(parent_id: params[:parent_id])
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
  # roomインスタンスまたはfolderインスタンスで表示するくらすを返す
  def display_icon_status(resource)
    resource.is_a?(Folder) ? 'glyphicon-folder-close' : 'glyphicon-list-alt'
  end

  # 編集へのリダイレクトパス
  # roomインスタンスまたはfolderインスタンスでパスを分ける
  def change_instance_redirect(resource)
    resource.is_a?(Folder) ? edit_folder_path(resource) : edit_room_path(resource)
  end
end

app/views/folders/_add_folder.html.erb
<ul class='clearfix table-add-list'>
  <li style='float: right;'>
    <a href="<%= new_room_path(folder_id: resource.id) %>"
      data-remote='true' class='btn btn-primary' style='margin: 20px 0;'
      data-toggle="tooltip" data-placement="top"
      title='新しくファイル管理フォルダを作成します'>
      + <i class='glyphicon glyphicon-list-alt'></i>
    </a>
  </li>

  <li style='float: right; margin: 0 30px 0 0;'>
    <a href="<%= new_folder_path(parent_id: resource.id) %>"
      data-remote='true' class='btn btn-primary' style='margin: 20px 0;'
      data-toggle="tooltip" data-placement="top"
      title='新しくフォルダを作成します'>
      + <i class='glyphicon glyphicon-folder-close'></i>
    </a>
  </li>
</ul>

app/views/folders/_folder.html.erb
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th class='text-center'>ファイル名</th>
        <th class='text-center'>備考</th>
      </tr>
    </thead>
    <% @folder.children.each do |folder| %>
      <tbody>
        <tr>
          <td><%= link_to folder.name, folder %></td>
          <td><%= folder.description %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/folders/_folder_table.html.erb
<div class='table-responsive'>
  <table class='table table-striped table-bordered table-hover'>
    <thead>
      <tr>
        <th class='text-center'>ファイル名</th>
        <th class='text-center'>備考</th>
        <th class='text-center' style='width: 60px;'>編集</th>
        <th class='text-center' style='width: 60px;'>削除</th>
      </tr>
    </thead>

    <% resources.each do |resource| %>
      <tbody>
        <tr>
          <td>
            <%= link_to resource do %>
              <i class="glyphicon <%= display_icon_status(resource) %>"></i>
              <%= resource.name %>
            <% end %>
          </td>

          <td><%= resource.description %></td>

          <td class='text-center'>
            <% if edit_permission_exist?(resource) %>
              <a href="<%= change_instance_redirect(resource) %>"
                data-remote='true'
                data-toggle="tooltip" data-placement="top"
                title='編集するにはクリックしてください'>
                <i style='font-size: 18px;' class='glyphicon glyphicon-edit'></i>
              </a>
            <% end %>
          </td>

          <td class='text-center'>
            <% if edit_permission_exist?(resource) %>
              <%= link_to resource, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i style='font-size: 18px; color: #EC5800;' class='glyphicon glyphicon-trash'></i>
              <% end %>
            <% end %>
          </td>
        </tr>
      </tbody>
    <% end %>
  </table>
</div>

app/views/folders/_form.html.erb
<div class='modal-dialog' role='document'>
  <div class='modal-content'>
    <div class='modal-header'>
      <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
        <span aria-hidden='true'>&times;</span>
      </button>
      <h4 class='modal-title' id='exampleModalLabel'><%= resource.name %>フォルダ</h4>
    </div>
    
    <div class='modal-body' style='padding-bottom: 0;'>
      <%= form_with(model: resource, remote: true) do |form| %>
        <%= resource_error_messages!(resource) %>

        <div class='form-group'>
          <%= form.label :name %>
          <%= form.text_field :name, class:'form-control' %>
        </div>

        <div class='form-group'>
          <%= form.label :description %>
          <%= form.text_area :description, class:'form-control', rows: 8 %>
        </div>

        <%= form.hidden_field :parent_id %>
        <%= form.hidden_field :user_id,  value: current_user.id %>
        <hr/>

        <div class='form-group'>
          <%= form.submit class:'form-control btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/folders/edit.js.erb
$("#folder-modal").html("<%= escape_javascript(render partial: 'form', locals: { resource: @resource }) %>")
$("#folder-modal").modal("show")

app/views/folders/index.html.erb
<div class='breadcrumbs'>
  <%= link_to 'Home', folders_path %> &rsaquo;
</div>

<%= render partial: 'add_folder', locals: { resource: @resource } %>
<%= render partial: 'folder_table', locals: { resources: @resources } %>

<div id='folder-modal' class='modal fade' tabindex='-1' role='dialog' aria-hidden='true'></div>
<div id='room-modal' class='modal fade' tabindex='-1' role='dialog' aria-hidden='true'></div>

<script>
  $(function () {
    var ua = navigator.userAgent;
    if (ua.indexOf('iPhone') > 0  ||
        ua.indexOf('Android') > 0 && ua.indexOf('Mobile') > 0 ||
        (ua.indexOf('iPad') > 0   || ua.indexOf('Android') > 0)) {
      $('[data-toggle="tooltip"]').tooltip('hide')
    } else {
      $('[data-toggle="tooltip"]').tooltip()
    }
  })
</script>

app/views/folders/new.js.erb
$("#folder-modal").html("<%= escape_javascript(render partial: 'form', locals: { resource: @resource }) %>")
$("#folder-modal").modal("show")

app/views/folders/show.html.erb
<% breadcrumb :folder, @root_below_folder %>

<%= render partial: 'add_folder', locals: { resource: @resource } %>
<%= render partial: 'folder_table', locals: { resources: @resources } %>

<div id='folder-modal' class='modal fade' tabindex='-1' role='dialog' aria-hidden='true'></div>
<div id='room-modal' class='modal fade' tabindex='-1' role='dialog' aria-hidden='true'></div>

<script>
  $(function () {
    var ua = navigator.userAgent;
    if (ua.indexOf('iPhone') > 0  ||
        ua.indexOf('Android') > 0 && ua.indexOf('Mobile') > 0 ||
        (ua.indexOf('iPad') > 0   || ua.indexOf('Android') > 0)) {
      $('[data-toggle="tooltip"]').tooltip('hide')
    } else {
      $('[data-toggle="tooltip"]').tooltip()
    }
  })
</script>