config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :folders
  resources :rooms, except: %i[index] do
    resources :documents, except: %i[index] do
      member do
        get :download
      end
    end
  end

  resources :user_controll_rooms, only: [:create, :destroy]

  devise_for :users, only: %i[sign_in sign_up sessions registrations]
  root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/document.rb
class Document < ApplicationRecord
  mount_uploader :uploaded_file, FileUploader
  validates :uploaded_file, presence: true

  belongs_to :user
  belongs_to :room

  scope :order_by_preference, -> { order(id: :desc) }

  ALLOW_DISPLAY_IMAGE = %w(
    .jpg
    .jpeg
    .png
    .gif
  ).freeze

  # `.jpg, .jpeg, .png, gif` のプレビュー画像を許可する
  def image?
    ALLOW_DISPLAY_IMAGE.include?(File.extname(uploaded_file.url).downcase)
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include CrudActionsMixin

  before_action :set_resource, only: %i[show edit update destroy download] # rubocop:disable Rails/LexicallyScopedActionFilter

  def download
    send_file(@resource.uploaded_file.current_path)
  end

  private

  def resource_params
    documents_params = params.require(:document).permit(:file_name, :file_date, :description, :user_id, :room_id)
    UploadFileService.new(documents_params).define_params
  end

  def set_resource
    @resource = model_name.find(params[:id])
    @room = @resource.room
  end

  def new_resource
    @room = Room.find(params[:room_id])
    @resource = model_name.new
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def update_pagination_partial_path(documents)
    if documents.next_page
      'rooms/rooms_pagination_page/update_pagination'
    else
      'rooms/rooms_pagination_page/remove_pagination'
    end
  end
end

app/views/documents/_add_document.html.erb
<ul class='clearfix table-add-list'>
  <li style='float: right; margin: 0 30px 0 0;'>
    <a href="<%= new_room_document_path(resource) %>"
      data-remote='true' class='btn btn-primary' style='margin: 20px 0;'
      data-toggle="tooltip" data-placement="top"
      title='新しくファイルを作成します'>
      + <i class='glyphicon glyphicon-copy' style='font-size: 18px;'></i>
    </a>
  </li>
</ul>
<div id='document-modal' class='modal fade' tabindex='-1' role='dialog' aria-hidden='true'></div>

app/views/documents/_document_table_body.html.erb
<tbody>
  <% documents.each do |document| %>
    <tr>
      <td>
        <%= link_to document.file_name, [resource, document] %>
        <%= link_to "/rooms/#{resource.id}/documents/#{document.id}/download", method: :get do %>
          <i class='glyphicon glyphicon-download' style='float: right;'></i>
        <% end %>
      </td>

      <td>
        <%= document.description %>
      </td>

      <td class='text-center' style='width: 60px;'>
        <% if edit_permission_exist?(document) %>
          <a href="<%= edit_room_document_path(resource, document) %>"
            data-remote='true'
            data-toggle="tooltip" data-placement="top"
            title='編集するにはクリックしてください'>
            <i style='font-size: 18px;' class='glyphicon glyphicon-edit'></i>
          </a>
        <% end %>
      </td>

      <td class='text-center' style='width: 60px;'>
        <% if edit_permission_exist?(document) %>
          <%= link_to [resource, document], method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i style='font-size: 18px; color: #EC5800;' class='glyphicon glyphicon-trash'></i>
          <% end %>
        <% end %>
      </td>
    </tr>
  <% end %>
</tbody>

app/views/documents/_documents_table.html.erb
<div class='table-responsive'>
  <table class='table table-striped table-bordered table-hover' id="feed">
    <thead>
      <tr>
        <th class='text-center'>ファイル名</th>
        <th class='text-center'>備考</th>
        <th class='text-center' style='width: 60px;'>編集</th>
        <th class='text-center' style='width: 60px;'>削除</th>
      </tr>
    </thead>
    <%= render partial: 'documents/document_table_body', locals: { resource: @resource, documents: @documents } %>

    <div class="infinite-scroll">
      <%= will_paginate @documents %>
    </div>
  </table>
</div>

app/views/documents/_form.html.erb
<div class='modal-dialog' role='document'>
  <div class='modal-content'>
    <div class='modal-header'>
      <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
        <span aria-hidden='true'>&times;</span>
      </button>
      <h4 class='modal-title' id='exampleModalLabel'>ファイル追加</h4>
    </div>
    
    <div class='modal-body' style='padding-bottom: 0;'>
      <%= form_with(model: [room, resource], :html => { multipart: true, remote: true }) do |form| %>
        <%= resource_error_messages!(resource) %>

        <div class='form-group'>
          <%= form.label :file_name %>
          <%= form.text_field :file_name, class:'form-control' %>
        </div>

        <div class='form-group'>
          <%= form.label :file_date %>
          <%= form.file_field :file_date %>
          <% if resource.uploaded_file.present? %>
            <p style='font-weight: normal;'>保存ファイル：<%= resource[:uploaded_file] %></p>
          <% end %>
        </div>

        <div class='form-group'>
          <%= form.label :description %>
          <%= form.text_area :description, class:'form-control', rows: 8 %>
        </div>

        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.hidden_field :room_id, value: room.id %>
        <hr/>

        <div class='form-group'>
          <%= form.submit class:'form-control btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/documents/edit.js.erb
$("#document-modal").html("<%= escape_javascript(render partial: 'form', locals: { resource: @resource, room: @room }) %>")
$("#document-modal").modal("show")

app/views/documents/new.js.erb
$("#document-modal").html("<%= escape_javascript(render partial: 'form', locals: { resource: @resource, room: @room }) %>")
$("#document-modal").modal("show")

app/views/documents/show.html.erb
<h2><%= @resource.file_name %>ファイルの詳細</h2>
<h3>
  <%= link_to room_path(@room), class: "btn btn-primary" do %>
    <i class='glyphicon glyphicon-menu-left'></i>
    ファイル管理一覧
  <% end %>
</h3>
<div id='document-modal' class='modal fade' tabindex='-1' role='dialog' aria-hidden='true'></div>

<div class="row">
  <div class="thumbnail">
    <% if @resource.image? %>
      <%= image_tag(@resource.uploaded_file.to_s) %>
    <% else %>
      <p>プレビューは表示されません。<p>
    <% end %>
    <div class="caption">
      <hr />
      <h4>備考欄</h4>
      <p><%= simple_format(@resource.description) %></p>
      <p>
        <% if edit_permission_exist?(@resource) %>
          <a href="<%= edit_room_document_path(@room, @resource) %>"
            data-remote='true'
            data-toggle="tooltip" data-placement="top"
            title='編集するにはクリックしてください'
            class='btn btn-default active'>
            <i style='font-size: 18px;' class='glyphicon glyphicon-edit'></i>
          </a>
        <% end %>

        <% if edit_permission_exist?(@resource) %>
          <%= link_to [@room, @resource], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default active' do %>
            <i style='font-size: 18px; color: #EC5800;' class='glyphicon glyphicon-trash'></i>
          <% end %>
        <% end %>
      </p>
    </div>
  </div>
</div>