config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :folders
  resources :rooms, except: %i[index] do
    resources :documents, except: %i[index] do
      member do
        get :download
      end
    end
  end

  resources :user_controll_rooms, only: [:create, :destroy]

  devise_for :users, only: %i[sign_in sign_up sessions registrations]
  root 'homes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  belongs_to :folder
  has_many   :documents, dependent: :destroy
  has_many   :messages, dependent: :destroy
  has_many   :user_controll_rooms, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  include CrudActionsMixin

  def show
    @messages = @resource.messages
    @documents = @resource.documents.order_by_preference.paginate(page: params[:page])
    @user_controll_room = UserControllRoom.find_by(user_id: current_user, room_id: @resource)
    respond_to do |format|
      format.html
      format.js { render partial: 'rooms/rooms_pagination_page' }
    end
  end

  private

  def resource_params
    params.require(:room).permit(:name, :description, :user_id, :folder_id)
  end

  def new_resource
    @resource = model_name.new(folder_id: params[:folder_id])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def like_room?(room)
    UserControllRoom.find_by(user_id: current_user, room_id: room.id).present?
  end
end

app/views/rooms/_chat_room.html.erb
<div class='chat_form'>
  <div class='panel panel-default'>
    <div class='panel-heading'>
      <h3 class='panel-title'>ファイル管理名 : <%= resource.name %></h3>
    </div>

    <div class='panel-body pre-scrollable scroll-bar' id='messages' data-room_id="<%= resource.id %>">
      <div class='message'>
        <%= render messages %>
      </div>
    </div>

    <div class='panel-body'>
      <form class='form-group'>
        <div class='col-sm-11'>
          <textarea type='text' id='message-box' data-behavior='room_speaker' class='form-control' placeholder='テキストを入力してください。' style='max-height: 100px;'></textarea>
        </div>
        
        <div class='col-sm-1'>
          <button type='button' id='send-btn' style='line-height: 40px; border-radius: 5px;'>送信</button>
        </div>

        <div class='col-sm-12'>
          <p>PCの場合は入力後Control + enter キーでも送信できます。</p>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/rooms/_form.html.erb
<div class='modal-dialog' role='document'>
  <div class='modal-content'>
    <div class='modal-header'>
      <button type='button' class='close' data-dismiss='modal' aria-label='Close'>
        <span aria-hidden='true'>&times;</span>
      </button>
      <h4 class='modal-title' id='exampleModalLabel'><%= resource.name %>ファイル管理</h4>
    </div>
    
    <div class='modal-body' style='padding-bottom: 0;'>
      <%= form_with(model: resource, remote: true) do |form| %>
        <%= resource_error_messages!(resource) %>

        <div class='form-group'>
          <%= form.label :name %>
          <%= form.text_field :name, class:'form-control' %>
        </div>

        <div class='form-group'>
          <%= form.label :description %>
          <%= form.text_area :description, class:'form-control', rows: 8 %>
        </div>

        <%= form.hidden_field :user_id, value: current_user.id %>
        <%= form.hidden_field :folder_id %>
        <hr/>

        <div class='form-group'>
          <%= form.submit class:'form-control btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/_rooms_pagination_page.js.erb
$('#feed').append('<%= j render partial: 'documents/document_table_body', \
                                locals: { resource: @resource, documents: @documents } %>');
<%= render update_pagination_partial_path(@documents) %>

app/views/rooms/edit.js.erb
$("#room-modal").html("<%= escape_javascript(render partial: 'form', locals: { resource: @resource }) %>")
$("#room-modal").modal("show")

app/views/rooms/new.js.erb
$("#room-modal").html("<%= escape_javascript(render partial: 'form', locals: { resource: @resource }) %>")
$("#room-modal").modal("show")

app/views/rooms/show.html.erb
<% breadcrumb :room, @resource %>

<div style='padding: 10px 0;'>
  <% if like_room?(@resource) %>
    <%= link_to 'お気に入りに登録済', user_controll_room_path(@user_controll_room, room_id: @resource.id), method: :DELETE, class: 'btn btn-default', style: 'width:100%;' %>
  <% else %>
    <%= link_to 'お気に入り登録', user_controll_rooms_path(room_id: @resource.id), method: :post, class: 'btn btn-primary', style: 'width:100%;' %>
  <% end %>
</div>

<%= render partial: 'chat_room', locals: { resource: @resource, messages: @messages } %>
<%= render partial: 'documents/add_document', locals: { resource: @resource } %>
<%= render partial: 'documents/documents_table' %>

<script>
  // リロードした時にファイル管理にあるメッセージスクロールテーブルを一番最新のメッセージまでスクロールする
  $(document).ready(function(){
    height = $('.scroll-bar')[0].scrollHeight
    $('.scroll-bar').scrollTop(height)
  });
</script>